const languageNames = {
  AF: 'Pashto, Dari',
  AL: 'Albanian',
  DZ: 'Arabic',
  AD: 'Catalan',
  AO: 'Portuguese',
  AG: 'English',
  AR: 'Spanish',
  AM: 'Armenian',
  AU: 'English',
  AT: 'German',
  AZ: 'Azerbaijani',
  BS: 'English',
  BH: 'Arabic',
  BD: 'Bengali',
  BB: 'English',
  BY: 'Belarusian, Russian',
  BE: 'Dutch, French, German',
  BZ: 'English',
  BJ: 'French',
  BT: 'Dzongkha',
  BO: 'Spanish, Quechua, Aymara, Guarani',
  BA: 'Bosnian, Croatian, Serbian',
  BW: 'English, Tswana',
  BR: 'Portuguese',
  BN: 'Malay',
  BG: 'Bulgarian',
  BF: 'French',
  BI: 'Kirundi, French, English',
  CV: 'Portuguese',
  KH: 'Khmer',
  CM: 'French, English',
  CA: 'English, French',
  CF: 'French, Sango',
  TD: 'French, Arabic',
  CL: 'Spanish',
  CN: 'Chinese',
  CO: 'Spanish',
  KM: 'Comorian, Arabic, French',
  CG: 'French',
  CR: 'Spanish',
  HR: 'Croatian',
  CU: 'Spanish',
  CY: 'Greek, Turkish',
  CZ: 'Czech',
  DK: 'Danish',
  DJ: 'French, Arabic',
  DM: 'English',
  DO: 'Spanish',
  EC: 'Spanish',
  EG: 'Arabic',
  SV: 'Spanish',
  'EN-AU': 'English',
  'EN-CA': 'English',
  'EN-GB': 'English',
  'EN-US': 'English',
  GQ: 'Spanish, French, Portuguese',
  ER: 'Tigrinya, Arabic, English',
  EE: 'Estonian',
  SZ: 'Swazi, English',
  ET: 'Amharic',
  FJ: 'English, Fijian, Hindi',
  FI: 'Finnish',
  FR: 'French',
  GA: 'French',
  GM: 'English',
  GE: 'Georgian',
  DE: 'German',
  GH: 'English',
  GR: 'Greek',
  GD: 'English',
  GT: 'Spanish',
  GN: 'French',
  GW: 'Portuguese',
  GY: 'English',
  HT: 'French, Haitian Creole',
  VA: 'Italian',
  HN: 'Spanish',
  HU: 'Hungarian',
  IS: 'Icelandic',
  IN: 'Hindi, English',
  ID: 'Indonesian',
  IR: 'Persian (Farsi)',
  IQ: 'Arabic, Kurdish',
  IE: 'Irish, English',
  IL: 'Hebrew',
  IT: 'Italian',
  JM: 'English',
  JP: 'Japanese',
  JO: 'Arabic',
  KZ: 'Kazakh, Russian',
  KE: 'Swahili, English',
  KI: 'English, Gilbertese',
  KW: 'Arabic',
  KG: 'Kyrgyz, Russian',
  LA: 'Lao',
  LV: 'Latvian',
  LB: 'Arabic',
  LS: 'English, Sesotho',
  LR: 'English',
  LY: 'Arabic',
  LI: 'German',
  LT: 'Lithuanian',
  LU: 'Luxembourgish, French, German',
  MG: 'Malagasy, French',
  MW: 'English, Chichewa',
  MY: 'Malay',
  MV: 'Dhivehi',
  ML: 'French',
  MT: 'Maltese, English',
  MH: 'Marshallese, English',
  MR: 'Arabic',
  MU: 'English, French',
  MX: 'Spanish',
  FM: 'English',
  MD: 'Romanian',
  MC: 'French',
  MN: 'Mongolian',
  ME: 'Montenegrin',
  MA: 'Arabic, Berber',
  MZ: 'Portuguese',
  MM: 'Burmese',
  NA: 'English',
  NR: 'Nauruan, English',
  NP: 'Nepali',
  NL: 'Dutch',
  NZ: 'English, Maori',
  NI: 'Spanish',
  NE: 'French',
  NG: 'English',
  KP: 'Korean',
  MK: 'Macedonian',
  NO: 'Norwegian',
  OM: 'Arabic',
  PK: 'Urdu, English',
  PW: 'Palauan, English',
  PS: 'Arabic',
  PA: 'Spanish',
  PG: 'Tok Pisin, English, Hiri Motu',
  PY: 'Spanish, Guarani',
  PE: 'Spanish',
  PH: 'Filipino, English',
  PL: 'Polish',
  PT: 'Portuguese',
  QA: 'Arabic',
  RO: 'Romanian',
  RU: 'Russian',
  RW: 'Kinyarwanda, French, English',
  KN: 'English',
  LC: 'English',
  VC: 'English',
  WS: 'Samoan, English',
  SM: 'Italian',
  ST: 'Portuguese',
  SA: 'Arabic',
  SN: 'French',
  RS: 'Serbian',
  SC: 'French, English, Seychellois Creole',
  SL: 'English',
  SG: 'Malay, English, Chinese, Tamil',
  SK: 'Slovak',
  SI: 'Slovene',
  SB: 'English',
  SO: 'Somali',
  ZA: 'Zulu, Xhosa, Afrikaans, English, etc.',
  KR: 'Korean',
  SS: 'English',
  ES: 'Spanish',
  LK: 'Sinhala, Tamil',
  SD: 'Arabic, English',
  SR: 'Dutch',
  SE: 'Swedish',
  CH: 'German, French, Italian, Romansh',
  SY: 'Arabic',
  TW: 'Mandarin',
  TJ: 'Tajik',
  TZ: 'Swahili, English',
  TH: 'Thai',
  TL: 'Portuguese, Tetum',
  TG: 'French',
  TO: 'Tongan, English',
  TT: 'English',
  TN: 'Arabic',
  TR: 'Turkish',
  TM: 'Turkmen',
  TV: 'Tuvaluan, English',
  UG: 'English, Swahili',
  UA: 'Ukrainian',
  AE: 'Arabic',
  GB: 'English',
  US: 'English',
  UY: 'Spanish',
  UZ: 'Uzbek',
  VU: 'Bislama, English, French',
  VE: 'Spanish',
  VN: 'Vietnamese',
  YE: 'Arabic',
  ZM: 'English',
  ZW: 'English, Shona, Sindebele',
};

export default function getLanguageName(languageCode) {
  return languageNames[languageCode] || 'Unknown';
}
