const languageNames = {
    'EN-GB': 'English',
    'SE': 'Swedish',
    'FR': 'French',
    'DE': 'German',
    'ES': 'Spanish',
    'IT': 'Italian',
    'PT': 'Portuguese',
    'NL': 'Dutch',
    'PL': 'Polish',
    'RU': 'Russian',
    'JA': 'Japanese',
    'KO': 'Korean',
    'ZH': 'Chinese',
    'HI': 'Hindi',
    'AR': 'Arabic',
    'TR': 'Turkish',
    'VI': 'Vietnamese',
    'TH': 'Thai',
    'UK': 'Ukrainian',
    'CS': 'Czech',
    'HU': 'Hungarian',
    'FI': 'Finnish',
    'DA': 'Danish',
    'NO': 'Norwegian',
    'SV': 'Slovenian',
    'RO': 'Romanian',
    'SK': 'Slovak',
    'HR': 'Croatian',
    'BG': 'Bulgarian',
    'EL': 'Greek',
    'LV': 'Latvian',
    'LT': 'Lithuanian',
    'ET': 'Estonian',
    'MS': 'Malay',
    'FA': 'Persian',
    'ID': 'Indonesian',
    'HE': 'Hebrew',
    'SW': 'Swahili',
    'UR': 'Urdu',
    'BN': 'Bengali',
    'GU': 'Gujarati',
    'TA': 'Tamil',
    'TE': 'Telugu',
    'KN': 'Kannada',
    'MR': 'Marathi',
    'PA': 'Punjabi',
    'OR': 'Oriya',
    'ML': 'Malayalam',
};

export default function getLanguageName(languageCode) {
    return languageNames[languageCode] || 'Unknown';
}